In [1]:
import pandas as pd
import numpy as np

Q1

Write a Pandas program to read a csv file from a specified source and print the
first 5 rows.
(Diamonds.csv)

In [2]:
df = pd.read_csv('diamonds.csv')
df.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

Q2

Write a Pandas program to read a dataset from diamonds DataFrame and
modify the default columns values and print the first 6 rows.

In [3]:
df.columns = df.columns.str.title()
df.head(6)

,Unnamed: 0,Carat,Cut,Color,Clarity,Depth,Table,Price,X,Y,Z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
5,6,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48

Q3

Write a Pandas program to select a series from diamonds DataFrame. Print
the content of the series.

In [4]:
df.Cut

0            Ideal
1          Premium
2             Good
3          Premium
4             Good
           ...
53935        Ideal
53936         Good
53937    Very Good
53938      Premium
53939        Ideal
Name: Cut, Length: 53940, dtype: str

Q4

Write a Pandas program to create a new 'Quality -color' Series (use bracket
notation to define the Series name) of the diamonds DataFrame.

In [5]:
df['Quality_color'] = pd.Series([np.nan])
df.head()

,Unnamed: 0,Carat,Cut,Color,Clarity,Depth,Table,Price,X,Y,Z,Quality_color
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,NaN
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,NaN
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,NaN
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,NaN
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,NaN

Q5

Write a Pandas program to find the number of rows and columns and data
type of each column of diamonds Dataframe.

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     53940 non-null  int64
 1   Carat          53940 non-null  float64
 2   Cut            53940 non-null  str
 3   Color          53940 non-null  str
 4   Clarity        53940 non-null  str
 5   Depth          53940 non-null  float64
 6   Table          53940 non-null  float64
 7   Price          53940 non-null  int64
 8   X              53940 non-null  float64
 9   Y              53940 non-null  float64
 10  Z              53940 non-null  float64
 11  Quality_color  0 non-null      float64
dtypes: float64(7), int64(2), str(3)
memory usage: 4.9 MB

Q6

Write a Pandas program to summarize only 'object' columns of the diamonds
Dataframe.

In [7]:
df.select_dtypes(include=['str']).info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cut      53940 non-null  str
 1   Color    53940 non-null  str
 2   Clarity  53940 non-null  str
dtypes: str(3)
memory usage: 1.2 MB

Q7

Write a Pandas program to rename two of the columns of the diamonds
Dataframe.

In [8]:
df.rename(columns=({'Unnamed: 0':'Index','Color':'Colour'}),inplace=True)
df.head()

,Index,Carat,Cut,Colour,Clarity,Depth,Table,Price,X,Y,Z,Quality_color
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,NaN
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,NaN
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,NaN
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,NaN
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,NaN

Q8

Write a Pandas program to rename all the columns of the diamonds
Dataframe.

In [9]:
df.columns = ['Index', 'Carats', 'Shape_Cuts', 'Colour', 'Clarity', 'Depth', 'Tables', 'Price',
       'A', 'B', 'C', 'QualityColor']
df.head()

,Index,Carats,Shape_Cuts,Colour,Clarity,Depth,Tables,Price,A,B,C,QualityColor
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,NaN
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,NaN
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,NaN
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,NaN
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,NaN

Q9

Write a Pandas program to remove the second column of the diamonds
Dataframe.

In [10]:
df.drop(columns=['Index'],inplace=True)
df.head()

,Carats,Shape_Cuts,Colour,Clarity,Depth,Tables,Price,A,B,C,QualityColor
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,NaN
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,NaN
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,NaN
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,NaN
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,NaN

Q10

Write a Pandas program to remove multiple columns at once of the diamonds
Dataframe.

In [11]:
df.drop(columns=['A','B','C','QualityColor'],inplace=True)
df.head()

   Carats Shape_Cuts Colour Clarity  Depth  Tables  Price
0    0.23      Ideal      E     SI2   61.5    55.0    326
1    0.21    Premium      E     SI1   59.8    61.0    326
2    0.23       Good      E     VS1   56.9    65.0    327
3    0.29    Premium      I     VS2   62.4    58.0    334
4    0.31       Good      J     SI2   63.3    58.0    335

Q11

Write a Pandas program to remove multiple rows at once (axis=0 refers to
rows) from diamonds dataframe.