In [1]:
import pandas as pd
import numpy as np

In [12]:
raw = pd.Series(['10','25','abc',None,'7.5'])
print(raw)
print(pd.to_numeric(raw, errors = 'coerce'))    # bad values -> Nan

0     10
1     25
2    abc
3    NaN
4    7.5
dtype: str
0    10.0
1    25.0
2     NaN
3     NaN
4     7.5
dtype: float64

In [4]:
print(pd.to_numeric(raw, errors = 'coerce').fillna(0).astype(int))  # bad values -> Nan -> 0 -> Convert to int

0    10
1    25
2     0
3     0
4     7
dtype: int64

In [6]:
# Boolean Filtering

In [7]:
df = pd.read_csv('tips.csv')
df.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251

In [8]:
print(df['total_bill'] > 30)  # boolean series (True,False)

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Name: total_bill, Length: 244, dtype: bool

In [9]:
print(df[df['total_bill'] > 30])   # row where it is True

     total_bill    tip  gender smoker   day    time  size  price_per_person  \
11        35.26   5.00  Female     No   Sun  Dinner     4              8.82
23        39.42   7.58    Male     No   Sat  Dinner     4              9.86
39        31.27   5.00    Male     No   Sat  Dinner     3             10.42
44        30.40   5.60    Male     No   Sun  Dinner     4              7.60
47        32.40   6.00    Male     No   Sun  Dinner     4              8.10
52        34.81   5.20  Female     No   Sun  Dinner     4              8.70
56        38.01   3.00    Male    Yes   Sat  Dinner     4              9.50
59        48.27   6.73    Male     No   Sat  Dinner     4             12.07
83        32.68   5.00    Male    Yes  Thur   Lunch     2             16.34
85        34.83   5.17  Female     No  Thur   Lunch     4              8.71
95        40.17   4.73    Male    Yes   Fri  Dinner     4             10.04
102       44.30   2.50  Female    Yes   Sat  Dinner     3             14.77
112       38.07   4.00    Male     No   Sun  Dinner     3             12.69
141       34.30   6.70    Male     No  Thur   Lunch     6              5.72
142       41.19   5.00    Male     No  Thur   Lunch     5              8.24
156       48.17   5.00    Male     No   Sun  Dinner     6              8.03
167       31.71   4.50    Male     No   Sun  Dinner     4              7.93
170       50.81  10.00    Male    Yes   Sat  Dinner     3             16.94
173       31.85   3.18    Male    Yes   Sun  Dinner     2             15.92
175       32.90   3.11    Male    Yes   Sun  Dinner     2             16.45
179       34.63   3.55    Male    Yes   Sun  Dinner     2             17.32
180       34.65   3.68    Male    Yes   Sun  Dinner     4              8.66
182       45.35   3.50    Male    Yes   Sun  Dinner     3             15.12
184       40.55   3.00    Male    Yes   Sun  Dinner     2             20.27
187       30.46   2.00    Male    Yes   Sun  Dinner     5              6.09
197       43.11   5.00  Female    Yes  Thur   Lunch     4             10.78
207       38.73   3.00    Male    Yes   Sat  Dinner     4              9.68
210       30.06   2.00    Male    Yes   Sat  Dinner     3             10.02
212       48.33   9.00    Male     No   Sat  Dinner     4             12.08
219       30.14   3.09  Female    Yes   Sat  Dinner     4              7.54
237       32.83   1.17    Male    Yes   Sat  Dinner     2             16.42
238       35.83   4.67  Female     No   Sat  Dinner     3             11.94

                Payer Name     CC Number Payment ID
11            Diane Macias  4.577820e+15    Sun6686
23          Lance Peterson  3.542580e+15     Sat239
39       Mr. Brandon Berry  6.011530e+15    Sat6373
44             Todd Cooper  5.038470e+11    Sun2274
47            James Barnes  3.552000e+15    Sun9677
52            Emily Daniel  4.291280e+15    Sun6165
56   James Christensen DDS  3.497940e+14    Sat8903
59             Brian Ortiz  6.596450e+15    Sat8139
83           Daniel Murphy  5.356180e+15   Thur8801
85             Shawna Cook  6.011790e+15   Thur7972
95           Aaron Bentley  1.800270e+14    Fri9628
102          Heather Cohen  3.797710e+14    Sat6240
112             Jeff Lopez  3.572870e+15     Sun591
141         Steven Carlson  3.526520e+15   Thur1025
142           Eric Andrews  4.356530e+15   Thur3621
156          Ryan Gonzales  3.523150e+15    Sun7518
167         Michael Lawson  3.566290e+15    Sun3719
170          Gregory Clark  5.473850e+15    Sat1954
173            Scott Perez  3.577120e+15    Sun9335
175        Nathan Reynolds  3.703070e+14    Sun5109
179           Brian Bailey  3.466560e+14    Sun9851
180       James Hebert DDS  6.761690e+11    Sun7544
182           Jose Parsons  4.112210e+15    Sun2337
184            Stephen Cox  3.547800e+15    Sun5140
187          David Barrett  4.792880e+15    Sun9987
197            Brooke Soto  5.544900e+15   Thur9313
207          Ricky Ramirez  3.478180e+14    Sat4505
210          Shawn Mendoza  3.018400e+13    Sat8361
212        Alex Williamson  6.762190e+11    Sat4590
219           Shelby House  5.020970e+11    Sat8863
237           Thomas Brown  4.284720e+15    Sat2929
238         Kimberly Crane  6.761840e+11    Sat9777

In [10]:
# Multiple Condition

In [13]:
print(df[(df['total_bill'] > 30) & (df['gender'] == 'Male')])

     total_bill    tip gender smoker   day    time  size  price_per_person  \
23        39.42   7.58   Male     No   Sat  Dinner     4              9.86
39        31.27   5.00   Male     No   Sat  Dinner     3             10.42
44        30.40   5.60   Male     No   Sun  Dinner     4              7.60
47        32.40   6.00   Male     No   Sun  Dinner     4              8.10
56        38.01   3.00   Male    Yes   Sat  Dinner     4              9.50
59        48.27   6.73   Male     No   Sat  Dinner     4             12.07
83        32.68   5.00   Male    Yes  Thur   Lunch     2             16.34
95        40.17   4.73   Male    Yes   Fri  Dinner     4             10.04
112       38.07   4.00   Male     No   Sun  Dinner     3             12.69
141       34.30   6.70   Male     No  Thur   Lunch     6              5.72
142       41.19   5.00   Male     No  Thur   Lunch     5              8.24
156       48.17   5.00   Male     No   Sun  Dinner     6              8.03
167       31.71   4.50   Male     No   Sun  Dinner     4              7.93
170       50.81  10.00   Male    Yes   Sat  Dinner     3             16.94
173       31.85   3.18   Male    Yes   Sun  Dinner     2             15.92
175       32.90   3.11   Male    Yes   Sun  Dinner     2             16.45
179       34.63   3.55   Male    Yes   Sun  Dinner     2             17.32
180       34.65   3.68   Male    Yes   Sun  Dinner     4              8.66
182       45.35   3.50   Male    Yes   Sun  Dinner     3             15.12
184       40.55   3.00   Male    Yes   Sun  Dinner     2             20.27
187       30.46   2.00   Male    Yes   Sun  Dinner     5              6.09
207       38.73   3.00   Male    Yes   Sat  Dinner     4              9.68
210       30.06   2.00   Male    Yes   Sat  Dinner     3             10.02
212       48.33   9.00   Male     No   Sat  Dinner     4             12.08
237       32.83   1.17   Male    Yes   Sat  Dinner     2             16.42

                Payer Name     CC Number Payment ID
23          Lance Peterson  3.542580e+15     Sat239
39       Mr. Brandon Berry  6.011530e+15    Sat6373
44             Todd Cooper  5.038470e+11    Sun2274
47            James Barnes  3.552000e+15    Sun9677
56   James Christensen DDS  3.497940e+14    Sat8903
59             Brian Ortiz  6.596450e+15    Sat8139
83           Daniel Murphy  5.356180e+15   Thur8801
95           Aaron Bentley  1.800270e+14    Fri9628
112             Jeff Lopez  3.572870e+15     Sun591
141         Steven Carlson  3.526520e+15   Thur1025
142           Eric Andrews  4.356530e+15   Thur3621
156          Ryan Gonzales  3.523150e+15    Sun7518
167         Michael Lawson  3.566290e+15    Sun3719
170          Gregory Clark  5.473850e+15    Sat1954
173            Scott Perez  3.577120e+15    Sun9335
175        Nathan Reynolds  3.703070e+14    Sun5109
179           Brian Bailey  3.466560e+14    Sun9851
180       James Hebert DDS  6.761690e+11    Sun7544
182           Jose Parsons  4.112210e+15    Sun2337
184            Stephen Cox  3.547800e+15    Sun5140
187          David Barrett  4.792880e+15    Sun9987
207          Ricky Ramirez  3.478180e+14    Sat4505
210          Shawn Mendoza  3.018400e+13    Sat8361
212        Alex Williamson  6.762190e+11    Sat4590
237           Thomas Brown  4.284720e+15    Sat2929

In [14]:
print(df[(df['total_bill'] > 30) & ~(df['gender'] == 'Male')])

     total_bill   tip  gender smoker   day    time  size  price_per_person  \
11        35.26  5.00  Female     No   Sun  Dinner     4              8.82
52        34.81  5.20  Female     No   Sun  Dinner     4              8.70
85        34.83  5.17  Female     No  Thur   Lunch     4              8.71
102       44.30  2.50  Female    Yes   Sat  Dinner     3             14.77
197       43.11  5.00  Female    Yes  Thur   Lunch     4             10.78
219       30.14  3.09  Female    Yes   Sat  Dinner     4              7.54
238       35.83  4.67  Female     No   Sat  Dinner     3             11.94

         Payer Name     CC Number Payment ID
11     Diane Macias  4.577820e+15    Sun6686
52     Emily Daniel  4.291280e+15    Sun6165
85      Shawna Cook  6.011790e+15   Thur7972
102   Heather Cohen  3.797710e+14    Sat6240
197     Brooke Soto  5.544900e+15   Thur9313
219    Shelby House  5.020970e+11    Sat8863
238  Kimberly Crane  6.761840e+11    Sat9777

In [15]:
# print(df[(df['total_bill'] > 30) & (df['gender'] != 'Male')])  -> same as above

In [16]:
print(df[(df['total_bill'] > 30) |(df['tip'] > 5)])

     total_bill    tip  gender smoker   day    time  size  price_per_person  \
11        35.26   5.00  Female     No   Sun  Dinner     4              8.82
23        39.42   7.58    Male     No   Sat  Dinner     4              9.86
39        31.27   5.00    Male     No   Sat  Dinner     3             10.42
44        30.40   5.60    Male     No   Sun  Dinner     4              7.60
47        32.40   6.00    Male     No   Sun  Dinner     4              8.10
52        34.81   5.20  Female     No   Sun  Dinner     4              8.70
56        38.01   3.00    Male    Yes   Sat  Dinner     4              9.50
59        48.27   6.73    Male     No   Sat  Dinner     4             12.07
83        32.68   5.00    Male    Yes  Thur   Lunch     2             16.34
85        34.83   5.17  Female     No  Thur   Lunch     4              8.71
88        24.71   5.85    Male     No  Thur   Lunch     2             12.36
95        40.17   4.73    Male    Yes   Fri  Dinner     4             10.04
102       44.30   2.50  Female    Yes   Sat  Dinner     3             14.77
112       38.07   4.00    Male     No   Sun  Dinner     3             12.69
116       29.93   5.07    Male     No   Sun  Dinner     4              7.48
141       34.30   6.70    Male     No  Thur   Lunch     6              5.72
142       41.19   5.00    Male     No  Thur   Lunch     5              8.24
155       29.85   5.14  Female     No   Sun  Dinner     5              5.97
156       48.17   5.00    Male     No   Sun  Dinner     6              8.03
167       31.71   4.50    Male     No   Sun  Dinner     4              7.93
170       50.81  10.00    Male    Yes   Sat  Dinner     3             16.94
172        7.25   5.15    Male    Yes   Sun  Dinner     2              3.62
173       31.85   3.18    Male    Yes   Sun  Dinner     2             15.92
175       32.90   3.11    Male    Yes   Sun  Dinner     2             16.45
179       34.63   3.55    Male    Yes   Sun  Dinner     2             17.32
180       34.65   3.68    Male    Yes   Sun  Dinner     4              8.66
181       23.33   5.65    Male    Yes   Sun  Dinner     2             11.66
182       45.35   3.50    Male    Yes   Sun  Dinner     3             15.12
183       23.17   6.50    Male    Yes   Sun  Dinner     4              5.79
184       40.55   3.00    Male    Yes   Sun  Dinner     2             20.27
187       30.46   2.00    Male    Yes   Sun  Dinner     5              6.09
197       43.11   5.00  Female    Yes  Thur   Lunch     4             10.78
207       38.73   3.00    Male    Yes   Sat  Dinner     4              9.68
210       30.06   2.00    Male    Yes   Sat  Dinner     3             10.02
211       25.89   5.16    Male    Yes   Sat  Dinner     4              6.47
212       48.33   9.00    Male     No   Sat  Dinner     4             12.08
214       28.17   6.50  Female    Yes   Sat  Dinner     3              9.39
219       30.14   3.09  Female    Yes   Sat  Dinner     4              7.54
237       32.83   1.17    Male    Yes   Sat  Dinner     2             16.42
238       35.83   4.67  Female     No   Sat  Dinner     3             11.94
239       29.03   5.92    Male     No   Sat  Dinner     3              9.68

                Payer Name     CC Number Payment ID
11            Diane Macias  4.577820e+15    Sun6686
23          Lance Peterson  3.542580e+15     Sat239
39       Mr. Brandon Berry  6.011530e+15    Sat6373
44             Todd Cooper  5.038470e+11    Sun2274
47            James Barnes  3.552000e+15    Sun9677
52            Emily Daniel  4.291280e+15    Sun6165
56   James Christensen DDS  3.497940e+14    Sat8903
59             Brian Ortiz  6.596450e+15    Sat8139
83           Daniel Murphy  5.356180e+15   Thur8801
85             Shawna Cook  6.011790e+15   Thur7972
88            Roger Taylor  4.410250e+12   Thur9003
95           Aaron Bentley  1.800270e+14    Fri9628
102          Heather Cohen  3.797710e+14    Sat6240
112             Jeff Lopez  3.572870e+15     Sun591
116            Shawn Blake  4.689080e+15      Sun22
141         Steven Carlson  3.526520e+15   Thur1025
142           Eric Andrews  4.356530e+15   Thur3621
155         Madison Wilson  4.210880e+15    Sun9176
156          Ryan Gonzales  3.523150e+15    Sun7518
167         Michael Lawson  3.566290e+15    Sun3719
170          Gregory Clark  5.473850e+15    Sat1954
172            Larry White  3.043260e+13    Sun9209
173            Scott Perez  3.577120e+15    Sun9335
175        Nathan Reynolds  3.703070e+14    Sun5109
179           Brian Bailey  3.466560e+14    Sun9851
180       James Hebert DDS  6.761690e+11    Sun7544
181              Jason Cox  6.556930e+15    Sun3402
182           Jose Parsons  4.112210e+15    Sun2337
183      Dr. Michael James  4.718500e+12    Sun6059
184            Stephen Cox  3.547800e+15    Sun5140
187          David Barrett  4.792880e+15    Sun9987
197            Brooke Soto  5.544900e+15   Thur9313
207          Ricky Ramirez  3.478180e+14    Sat4505
210          Shawn Mendoza  3.018400e+13    Sat8361
211         Christopher Li  6.011960e+15    Sat6735
212        Alex Williamson  6.762190e+11    Sat4590
214        Marissa Jackson  4.922300e+15    Sat3374
219           Shelby House  5.020970e+11    Sat8863
237           Thomas Brown  4.284720e+15    Sat2929
238         Kimberly Crane  6.761840e+11    Sat9777
239          Michael Avila  5.296070e+15    Sat2657

In [17]:
# Membership and range

In [18]:
df[df['day'].isin(['Sat','Sun'])].shape

(163, 11)

In [22]:
df[df['total_bill'].between(10,20)].shape  # 10 <= bill <= 20 (both include)

(130, 11)

In [23]:
df[df['total_bill'].between(10,20,inclusive='left')].shape  # 10 <= bill < 20 (First include)

(130, 11)

In [24]:
# Text Column

In [25]:
df[df['Payer Name'].str.contains('Smith',case=False)]

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,2.131400e+14,Sun9679
76,17.92,3.08,Male,Yes,Sat,Dinner,2,8.96,Mark Smith,6.761880e+11,Sat9908
114,25.71,4.00,Female,No,Sun,Dinner,3,8.57,Katie Smith,5.400160e+15,Sun6492
152,17.26,2.74,Male,No,Sun,Dinner,3,5.75,Gregory Smith,4.292360e+12,Sun5205
154,19.77,2.00,Male,No,Sun,Dinner,4,4.94,James Smith,2.131700e+14,Sun5814

In [26]:
df[df['Payment ID'].str.startswith('Sun')]

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
186,20.90,3.50,Female,Yes,Sun,Dinner,3,6.97,Heidi Atkinson,4.422860e+15,Sun4254
187,30.46,2.00,Male,Yes,Sun,Dinner,5,6.09,David Barrett,4.792880e+15,Sun9987
188,18.15,3.50,Female,Yes,Sun,Dinner,3,6.05,Glenda Wiggins,5.783290e+11,Sun430
189,23.10,4.00,Male,Yes,Sun,Dinner,3,7.70,Richard Stevens,3.560190e+15,Sun1821
190,15.69,1.50,Male,Yes,Sun,Dinner,2,7.84,Riley Barnes,1.800540e+14,Sun5104

In [28]:
# Same condition , 4 syntaxes

In [36]:
filtered1 = df[(df['gender'] == 'Female') & (df['tip'] >=4)]
filtered1.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4.577820e+15,Sun6686
52,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4.291280e+15,Sun6165
73,25.28,5.00,Female,Yes,Sat,Dinner,2,12.64,Julie Holmes,5.418690e+15,Sat6065
85,34.83,5.17,Female,No,Thur,Lunch,4,8.71,Shawna Cook,6.011790e+15,Thur7972
93,16.32,4.30,Female,Yes,Fri,Dinner,2,8.16,Natalie Nguyen,5.181240e+15,Fri6963

In [35]:
min_tip = 4
filtered2 = df.query("gender == 'Female' and tip >= @min_tip")
filtered2.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4.577820e+15,Sun6686
52,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4.291280e+15,Sun6165
73,25.28,5.00,Female,Yes,Sat,Dinner,2,12.64,Julie Holmes,5.418690e+15,Sat6065
85,34.83,5.17,Female,No,Thur,Lunch,4,8.71,Shawna Cook,6.011790e+15,Thur7972
93,16.32,4.30,Female,Yes,Fri,Dinner,2,8.16,Natalie Nguyen,5.181240e+15,Fri6963

In [34]:
filtered3 = df.loc[(df['gender'] == 'Female') & (df['tip'] >= 4),['total_bill','tip','day']]
filtered3.head()

    total_bill   tip   day
11       35.26  5.00   Sun
52       34.81  5.20   Sun
73       25.28  5.00   Sat
85       34.83  5.17  Thur
93       16.32  4.30   Fri

In [33]:
df['tip'].where(df['tip'] >= 4)

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
239    5.92
240     NaN
241     NaN
242     NaN
243     NaN
Name: tip, Length: 244, dtype: float64