Q1. Write a Pandas program to create

a) Datetime object for Jan 15 2012.\
b) Specific date and time of 9:20 pm.\
c) Local date and time.\
d) A date without time.\
e) Current date.\
f) Time from a datetime.\
g) Current local time.

In [1]:
import pandas as pd
import datetime

In [2]:
date = pd.to_datetime('Jan 15 2012')
print('Year :-',date.year)
print('Month :-',date.month)
print('Day :-',date.day)
print('Day Of Week :-',date.day_name())

Year :- 2012
Month :- 1
Day :- 15
Day Of Week :- Sunday

In [3]:
ts = pd.Timestamp('Jan 15 2012 21:20:00')
print('Specific date and time of 9:20 pm :-',ts)

Specific date and time of 9:20 pm :- 2012-01-15 21:20:00

In [4]:
print('Local Date & Time :-',datetime.datetime.now())
print('Local Date & Time :-',pd.Timestamp.now())

Local Date & Time :- 2026-10-13 13:57:30.104406
Local Date & Time :- 2026-10-13 13:57:30.104610

In [5]:
print('----- Using DateTime -----')
print('Current Date :-',datetime.datetime.now().date())
print('Current Time :-',datetime.datetime.now().time())

print('\n----- Using Timestamp -----')
print('Current Date :-',pd.Timestamp.now().date())
print('Current Time :-',pd.Timestamp.now().time())

----- Using DateTime -----
Current Date :- 2026-10-13
Current Time :- 13:57:30.120774

----- Using Timestamp -----
Current Date :- 2026-10-13
Current Time :- 13:57:30.121223

In [6]:
print('Time From a Datetime :-',ts.time().strftime("%I:%M:%S %p"))

Time From a Datetime :- 09:20:00 PM

In [7]:
print('Current Local Time :-',pd.Timestamp.now().time().strftime('%I:%M:%S %p'))

Current Local Time :- 01:57:30 PM

Q2. Write a Pandas program to create

a) a specific date using timestamp.\
b) date and time using timestamp.\
c) a time adds in the current local date using timestamp.\
d) current date and time using timestamp.

In [8]:
pd.Timestamp('30 october 2026')

Timestamp('2026-10-30 00:00:00')

In [9]:
pd.Timestamp('30 october 2026 07:30:00')

Timestamp('2026-10-30 07:30:00')

In [10]:
local_date = pd.Timestamp('30 october 2026')
local_date + pd.Timedelta(days=2, hours=5, minutes=30)

Timestamp('2026-11-01 05:30:00')

In [11]:
print('Current Date & Time :-',pd.Timestamp.now())

Current Date & Time :- 2026-10-13 13:57:30.214435

Q3

Write a Pandas program to create a date from a given year, month, day and
another date from a given string formats.

In [12]:
year = 2026
month = 10
day = 30

date = pd.Timestamp(year = year, month = month, day = day)
print('From Give Details :-',date)

date_from_str_standard = pd.Timestamp("2026-10-30 14:30:00")
date_from_str_text = pd.Timestamp("October 30, 2026")

print("Dates from string formats:")
print(f"From standard string: {date_from_str_standard}")
print(f"From text string: {date_from_str_text}")

From Give Details :- 2026-10-30 00:00:00
Dates from string formats:
From standard string: 2026-10-30 14:30:00
From text string: 2026-10-30 00:00:00

Q4

Write a Pandas program to print the day after and before a specified date. Also
print the days between two given dates.

In [13]:
date = pd.Timestamp('2026-10-30')
print('Specified Date :-',date.date(),' Day :-',date.day_name())

before = date - pd.Timedelta(days=1)
print('Before Date :-',before.date(),' Day :-',before.day_name())

after = date + pd.Timedelta(days=1)
print('After Date :-',after.date(),' Day :-',after.day_name())

start_date = pd.Timestamp("2026-10-30")
end_date = pd.Timestamp("2026-11-15")
duration = end_date - start_date
print(f'Days Between {start_date.date()} & {end_date.date()} :- {duration.days}')

Specified Date :- 2026-10-30  Day :- Friday
Before Date :- 2026-10-29  Day :- Thursday
After Date :- 2026-10-31  Day :- Saturday
Days Between 2026-10-30 & 2026-11-15 :- 16

Q5

Write a Pandas program to create a time-series with two index labels and
random values. Also print the type of the index.

In [14]:
time_series = pd.date_range('2026-10-30',periods=3,freq='D')
data = {'Sale' :[100,120,90,125,110,60]}

stores = ['Store A','Store B']

multi_index = pd.MultiIndex.from_product([time_series,stores],names=['Date','Series'])
df = pd.DataFrame(data,index=multi_index)
print(f'Index Type :-{type(df.index)}')
df

Index Type :-<class 'pandas.MultiIndex'>

                    Sale
Date       Series
2026-10-30 Store A   100
           Store B   120
2026-10-31 Store A    90
           Store B   125
2026-11-01 Store A   110
           Store B    60

Q6

Write a Pandas program to create a time-series from a given list of dates as
strings.

In [15]:
dates = ['2026-10-11','2026-10-15','2027-01-01']
ts = pd.to_datetime(dates)

data = [10,20,30]

pd.Series(data, index=ts,name='Time-Series')

2026-10-11    10
2026-10-15    20
2027-01-01    30
Name: Time-Series, dtype: int64

Q7

Write a Pandas program to create a time series object that has time indexed
data. Also select the dates of same year and select the dates between certain
dates.

In [16]:
dates = ['2026-10-11','2026-10-15','2026-10-12','2026-10-13','2026-10-14']
ts = pd.to_datetime(dates)
data = [10,20,30,40,50]

time_series = pd.Series(data, index=ts,name='Time-Series')
time_series.sort_index(inplace=True)
time_series.loc['2026-10-11':'2026-10-14']

2026-10-11    10
2026-10-12    30
2026-10-13    40
2026-10-14    50
Name: Time-Series, dtype: int64

Q8

Write a Pandas program to create a date range using a startpoint date and a
number of periods.

In [17]:
dates = pd.date_range('30-10-2026', periods=20,freq='D')
dates

DatetimeIndex(['2026-10-30', '2026-10-31', '2026-11-01', '2026-11-02',
               '2026-11-03', '2026-11-04', '2026-11-05', '2026-11-06',
               '2026-11-07', '2026-11-08', '2026-11-09', '2026-11-10',
               '2026-11-11', '2026-11-12', '2026-11-13', '2026-11-14',
               '2026-11-15', '2026-11-16', '2026-11-17', '2026-11-18'],
              dtype='datetime64[us]', freq='D')

Q9

Write a Pandas program to create a whole month of dates in daily frequencies.
Also find the maximum, minimum timestamp and indexs.

In [18]:
dates = pd.date_range(start='2026-10-01',end='2026-10-31',freq='D')
print('Minimum :-',dates.min())
print('Index :-',dates.argmin())

print('Minimum :-',dates.max())
print('Index :-',dates.argmax())

Minimum :- 2026-10-01 00:00:00
Index :- 0
Minimum :- 2026-10-31 00:00:00
Index :- 30

Q10

Write a Pandas program to create a time series using three months
frequency.

In [19]:
pd.date_range('2026-01-01',periods=6,freq='3MS')

DatetimeIndex(['2026-01-01', '2026-04-01', '2026-07-01', '2026-10-01',
               '2027-01-01', '2027-04-01'],
              dtype='datetime64[us]', freq='3MS')

Q11

Write a Pandas program to create a sequence of durations increasing by an
hour.

In [21]:
duration_sequence = pd.timedelta_range(start='0 hours', periods=10, freq='h')
duration_sequence

TimedeltaIndex(['0 days 00:00:00', '0 days 01:00:00', '0 days 02:00:00',
                '0 days 03:00:00', '0 days 04:00:00', '0 days 05:00:00',
                '0 days 06:00:00', '0 days 07:00:00', '0 days 08:00:00',
                '0 days 09:00:00'],
               dtype='timedelta64[us]', freq='h')

Q12

Write a Pandas program to convert year and day of year into a single
datetime column of a dataframe.

In [33]:
date = pd.to_datetime('30-10-2026',dayfirst=True)
df = pd.DataFrame({
    'Year':[date.year],
    'Date':[date.day]})
df

   Year  Date
0  2026    30

Q13

Write a Pandas program to create a series of Timestamps from a DataFrame of integer or string columns. Also create a series of Timestamps using specified
columns.

In [36]:
data = {
    'year':[2010,'2012',2015],
    'month':[10,2,7],
    'day': ['12', '25', '13'], 
    'hour':[1,5,6]
}
df = pd.DataFrame(data)
df

   year  month day  hour
0  2010     10  12     1
1  2012      2  25     5
2  2015      7  13     6

In [41]:
sr = pd.to_datetime(df[['year','month','day']])
sr

0   2010-10-12
1   2012-02-25
2   2015-07-13
dtype: datetime64[us]

Q14 

Write a Pandas program to check if a day is a business day (weekday) or not.

In [43]:
df = pd.DataFrame({
    'date': pd.to_datetime(['2026-10-12', '2026-10-13', '2026-10-16', '2026-10-17', '2026-10-18'])
})
df

        date
0 2026-10-12
1 2026-10-13
2 2026-10-16
3 2026-10-17
4 2026-10-18

In [49]:
df[df['date'].dt.dayofweek < 5]

        date
0 2026-10-12
1 2026-10-13
2 2026-10-16

Q15

Write a Pandas program to get a time series with the last working days of
each month of a specific year.

In [52]:
year = 2026
last_working_days = pd.date_range(start=f'{year}-01-01', end=f'{year}-12-31', freq='BME')
df = pd.DataFrame({
    'Last Working Day': last_working_days,
    'Day of Week': last_working_days.day_name()
})
df

   Last Working Day Day of Week
0        2026-01-30      Friday
1        2026-02-27      Friday
2        2026-03-31     Tuesday
3        2026-04-30    Thursday
4        2026-05-29      Friday
5        2026-06-30     Tuesday
6        2026-07-31      Friday
7        2026-08-31      Monday
8        2026-09-30   Wednesday
9        2026-10-30      Friday
10       2026-11-30      Monday
11       2026-12-31    Thursday

Q16

Write a Pandas program to create a time series combining hour and minute.

In [ ]:
  df = pd.DataFrame({
    'hour':,
    'minute': [0, 30, 45, 15]
})

base_date = pd.to_datetime('2026-10-13')
df['timestamp'] = (
    base_date 
    + pd.to_timedelta(df['hour'], unit='H') 
    + pd.to_timedelta(df['minute'], unit='T')
)
df